baseURL = 'http://webhugo.s3-website-us-east-1.amazonaws.com/'
languageCode = 'en-us'
title = "Marlon's blog"
theme = "web"

[menu]
  [[menu.main]]
    identifier = "Blog"
    pre = ""
    post = ""
    name = "Blog"
    url = "/posts/"
    title = "Blog"
    weight = 1
  [[menu.main]]
    identifier = "Tags"
    pre = ""
    post = ""
    name = ""
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "category"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Category"
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/mmc00"
  dateFormat = "2006-01-02"
  title = "Data Scientist, Economist and Cloud Engineer in process"
  images = ["about.jpg"]
  
 [params.app]
  title = "Marlon's blog"
 
  [params.home.profile]
    subtitle = "Data Scientist, Economist and Cloud Engineer in process"