baseURL = 'http://webhugo.s3-website-us-east-1.amazonaws.com/'
languageCode = 'en-us'
title = "Marlon's blog"
theme = "web"

[menu]
  [[menu.main]]
    identifier = "Blog"
    pre = ""
    post = ""
    name = "Blog"
    url = "/posts/"
    title = "Blog"
    weight = 1
  [[menu.main]]
    identifier = "Tags"
    pre = ""
    post = ""
    name = ""
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "category"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Category"
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/mmc00"
  dateFormat = "2006-01-02"
  title = "Data Scientist, Economist and Cloud Engineer in process"
  images = ["about.jpg"]
  
 [params.app]
  title = "Marlon's blog"
 
  [params.home.profile]
    subtitle = "Data Scientist, Economist and Cloud Engineer in process"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Marlon"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
    since = 2019
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
    
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "about.jpg"
      title = "Marlon Molina Corella"
      subtitle = "Data Scientist, Economist and Cloud Engineer in process"
      typeit = true
      social = true
      disclaimer = "Economy, Math, Cloud"
      
    [params.home.posts]
      enable = true
      paginate = 20
      defaultHiddenFromHomePage = true
      
 [params.social]
    GitHub = "https://github.com/mmc00"
    Linkedin = "https://www.linkedin.com/in/marlon-molina-corella-413a3610a"
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "marlonmolina00@hotmai.com"
    RSS = false # LoveIt NEW | 0.2.0